//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

   

    public partial class Hakkimizda
    {
        public int HakkimizdaID { get; set; }
        public string Resim { get; set; }
        public string Baslik { get; set; }
        public string AltBaslik { get; set; }
        public string Icerik { get; set; }
        public string UstBaslik { get; set; }
        public virtual HttpPostedFileBase resimfile {get;set;}

    }
}
